### PR TITLE
upgrade to scoverage 1.4

### PR DESCRIPTION
**Pull request by maiflai**
* exclusion patterns appear to be broken upstream
 * still investigating other breaks

### CODE REVIEW

**Comment by maiflai** [comment]
Dependencies:

* https://github.com/scoverage/scalac-scoverage-plugin/pull/276
* https://github.com/scoverage/scalac-scoverage-plugin/issues/278

**Comment by eyalroth** [comment]
Should we add a (functional) test case for running with `1.3.1` with these changes to see they didn't break backward compatibility?

**Comment by maiflai** [comment]
Unfortunately they depend on a new function in 1.4 - do you think that's ok?

**Comment by eyalroth** [comment]
Yeah I can see that `IOUtils.reportFileSearch` has been replaced with `IOUtils.scoverageDataDirsSearch`, so there's actually no way to maintain backward compatibility.

That makes sense though; this plugin isn't really supposed to add any additional functionality and is just a "proxy" for the scalac plugin. In fact, defining a custom scalac plugin version (via `scoverageVersion`) should be experimental at best, much like [it is with the maven plugin](https://github.com/scoverage/scoverage-maven-plugin#scalac-scoverage-plugin-version-configuration). Let's just update the README to clarify that :)

**Comment by maiflai** [comment]
@gslowikowski - please would it be possible to get https://github.com/scoverage/scalac-scoverage-plugin/pull/276 merged into a Snapshot so that we can test this?

Thanks,
Stu

**Comment by eyalroth** [comment]
@maiflai We should probably update the part in the README about the `scoverageVersion` option; we should note that (a) the default value has changed, (b) the plugin is compatible only with 1.4+ versions, and (c) it is experimental.

**Comment by maiflai** [comment]
yes, agree on (a) and (b) but not sure what you mean by (c)? it's new, but I wouldn't call it experimental.

I do think we should release this as a new major version of the Gradle plugin - as you pointed out before, the behaviour of the plugin has changed significantly. I'll add notes to the upgrading section.

**Comment by eyalroth** [comment]
It is experimental as it might not be compatible with future versions of the scalac plugin (as happened in this case). I guess it's not crucial to mention that, though :)

**Pull request merged**
