### PR TITLE
Make the plugin compatible with Palantir's consistent versions plugin

### LINKED ISSUE #140: Scoverage Plugin Resolving dependencies at configuration time
I'm having some issues using the `gradle-scoverage` plugin alongside [radle-consistent-versions](https://github.com/palantir/gradle-consistent-versions). `gradle-consistent-versions` enforces that no dependencies are resolved at compile time( [see](https://github.com/palantir/gradle-consistent-versions#resolving-dependencies-at-configuration-time-is-banned)).

I opened an issue with `gradle-consistent-versions` https://github.com/palantir/gradle-consistent-versions/issues/494 , but ended up closing that and opening one here instead.

Is this something you are open to fixing? I'm happy to attempt writing a patch if that is the case (still new to gradle plugin development though).

### PR DESCRIPTION
**Pull request by eyalroth**
Fixes #140.

This PR introduces a small change in behavior. The Scala version of the scoverage dependencies will now only be automatically detected if the `scoverageScalaVersion` is not defined. Previously, it overrided that option regardless if it was defined or not.

Note the changes to the `README.md` file explaining how to make a build compatible with the Palantir plugin (need to manually configure the Scala version via `scoverageScalaVersion`).

### CODE REVIEW

**Comment by y0ns0n** [comment]
Any chance we could get this merged?

**Comment by eyalroth** [comment]
@maiflai care to take a look? :)

**Comment by maiflai** [comment]
thanks both - there seems to be recent activity upstream, is it ok to wait for a little bit to see if a release is coming out there?

**Comment by y0ns0n** [comment]
What's the timeline for that? I work on a large monorepo which would greatly benefit from the performance improvements that this change would provide, so would vote for a release sooner rather than later.

**Pull request merged**
