### PR TITLE
(#125) fix compatibility with scala 2.11

### PR DESCRIPTION
**Pull request by pan3793**
Fixes https://github.com/scoverage/gradle-scoverage/issues/125

### CODE REVIEW

**Comment by eyalroth** [comment]
Thank you for this fix. Looks like the cross-version test was broken (addressed in #127).

Could you edit the description to "Fixes #125"? It will make sure the ticket is closed once the PR is merged.

**Comment by pan3793** [comment]
@eyalroth Thanks for your guidance, description has been changed.

**Comment by maiflai** [comment]
Thanks both.

Please can I confirm something though? I expected that merging @eyalroth's test change would break master, but it doesn't.

Is there still a missing test case?

I should have fixed this upstream as part of the 1.4.1 change, but I missed the opportunity.

Stu.

**Comment by eyalroth** [comment]
@maiflai I also expected my PR to not pass the checks. The changed test does fail on my machine, both when running from windows and linux (WSL), with either Oracle's JDK or OpenJDK.

Perhaps [the check](https://travis-ci.org/scoverage/gradle-scoverage/builds/617776440) passes because it doesn't clean the project?
```
$ ./gradlew assemble
$ ./gradlew --info --stacktrace check
```

**Comment by eyalroth** [comment]
@maiflai Hmm I think the problem is actually that other functional tests are running before the cross-version test in the same JVM. I tried to remedy that in #128 by running the cross-version test before all the other functional tests. If my theory is correct, then #128 should now fail the check.

**Pull request merged**
