### PR TITLE
Fix deprecation warnings about undeclared dependency (round 2)

### LINKED ISSUE #163: Gradle 7 incompatibility due to implicit dependency
Running `gradle-scoverage` under Gradle 7 (in this case `7.1.1.`) results in the following warnings for multiple coverage tasks: 

```
> Task :some-module:jar
Execution optimizations have been disabled for task ':some-module:jar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/some-module/build/libs/some-module.jar'. Reason: Task ':some-module:reportTestScoverage' uses this output of task ':some-module:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

Can you please check this issue?

### PR DESCRIPTION
**Pull request by eyalroth**
Fixes #163 (again).

This PR achieves the following:
1. Upgrade the gradle wrapper to `7.1.1` (to get the deprecation warnings).
2. Add a CI job that fails on any warning, but doesn't fail the overall build.
3. Fix the deprecation warning by making the report and aggregation tasks declare their "sources" only on the actual source files and not the entire project directory. This changes the path of the report files (removes the `src/main/scala` prefix).

The changes in `ScoverageWriter.java` make use of the `Seq` constructors of the various writers imported from the scalac plugin, while making it possible to compile this plugin once and be able to work with either scala (and scalac plugin) 2.12 or 2.13.

### CODE REVIEW

**Comment by eyalroth** [comment]
@maiflai Let me know if this is possible to merge this PR even though one of the check fails (more deprecation warnings).

If not, then I'll change the CI configuration to not fail the "fail on warning" job but only fail the gradle step.

**Comment by maiflai** [comment]
interesting - not sure what the impact on the build status will be if we move to having a matrix build.

perhaps we should have a separate action if we don't plan to fix this immediately?

also, could we update to 7.2 which I think is now available?

**Comment by eyalroth** [comment]
> interesting - not sure what the impact on the build status will be if we move to having a matrix build.
> 
> perhaps we should have a separate action if we don't plan to fix this immediately?

The overall build action is successful, as can be seen [here](https://github.com/scoverage/gradle-scoverage/actions/runs/1177635357), but I don't know if it blocks a PR from merging or not. This is most likely configurable in the repository settings, under the protection rule for `master`.

I think it would be better if the PR would show that a check has failed even though it doesn't block it, as long as we fix this check now (I'm planning a separate PR) and try and keep it in the green in the future.

**Comment by maiflai** [comment]
I think that it can be merged without a successful action. I think that it would need someone with greater powers than me to change this, I don't have access to repository settings.

Can the other PR be merged now?

**Comment by eyalroth** [comment]
@maiflai Then I think that's the ideal situation; i.e, when the build with warnings fails it shows up in the PR as a failed check but doesn't block it from being merged.

And on that note, yes this PR can be merged and then #169 as well.

**Pull request merged**
