### PR TITLE
Support for tests in separate project

### PR DESCRIPTION
**Pull request by Kwestor**
To be reviewed and merged after #37 and #42 - it bases on those PRs.

Tests are written by me, solution to make them work by @maiflai - big thanks!

For my part, disclaimer required by the lawyers (it's covered by Apache 2, but they want me to include it in PR description):

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

### CODE REVIEW

**Comment by Kwestor** [comment]
Do not merge - last commit fails on windows and passes on Linux by accident (results are still incorrect).

**Comment by maiflai** [comment]
Unfortunately the report is broken because the compilation of the class in `a-tests/src/main/scala` overwrites the measurement file created earlier during the instrumentation of `a/src/main/scala`.

The `a` main classes remain instrumented, so I expect that we will see a corrupted report where statements from `a` are attributed to statements from `a-tests`.

@sksamuel - I think this is related to the discussion earlier about multiple compilation runs? https://github.com/scoverage/scalac-scoverage-plugin/issues/81#issuecomment-72321603

**Comment by maiflai** [comment]
From my perspective it's an uncommon project structure, but I think we should be able to support such a thing.

**Comment by Kwestor** [comment]
I was puzzled at first why it's structured this way, but it makes sense if you think about it:

- `a`
  - `main` (code to test here)
- `a-tests` (depends on `a`)
  - `main` (commons for testing `a`-related stuff)
  - `test` (tests for `a`)
- `b` (depends on `a`)
- `b-tests` (dependes on commons from `a-tests`)

This way you don't have to publish test artifacts from `a-tests` to use it in `b-tests`. And you do publish only the commons for tests, not everything.

**Comment by maiflai** [comment]
I'll see if my git-fu improves overnight, but I think that adding the following to the test subproject configuration helps things:

```groovy
  sourceSets {
    testScoverage {
      compileClasspath += sourceSets.main.output
      runtimeClasspath += sourceSets.main.output
    }
  }
  compileScoverageScala {
    onlyIf { false }
  }
```

This instructs gradle to not instrument `a-tests/src/main/scala` and use the un-instrumented classes instead.

**Comment by sksamuel** [comment]
@maiflai what's the status with these PRs ?

**Comment by Kwestor** [comment]
Thanks!

**Pull request merged**
