### PR TITLE
Do not fail on missing scoverage compile task in dependency

### PR DESCRIPTION
**Pull request by JozoVilcek**
Fix for https://github.com/scoverage/gradle-scoverage/issues/136

### CODE REVIEW

**Comment by eyalroth** [comment]
Looks good, thank you for the contribution!

Could you add a new functional test which replicates the bug? Take a look at the `functionalTest` directory for reference. Also, I believe that this particular test case only needs a "dry run", since it tests the configuration and not the actual execution of the plugin.

**Comment by JozoVilcek** [comment]
@eyalroth I can try. Do you prefer to edit one of existing projects (which one?) or create a new one specifically for this purpose?

**Comment by eyalroth** [comment]
I think a new project is preferable; otherwise, this will make the other existing projects more complex than they should be.

**Comment by JozoVilcek** [comment]
@eyalroth can you take a loot at change and suggest further changes to the tests if needed? Thanks

**Comment by eyalroth** [comment]
@JozoVilcek Oh I wasn't notified on your force-push. The test looks good, as long as it fails without the fix :)

**Comment by JozoVilcek** [comment]
@maiflai do you have time to look at this PR?

**Pull request merged**
